apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: 5.0.2     # ">=1.0.0-alpha"
  test:
    enable: true      #false
  values:
    ingress:
      hosts:
        - podinfo.staging
